#!/usr/bin/env python

import argparse
import sys, os

from tmDiff import menudiff
from tmDiff import __version__

FMT_UNIFIED = 'unified'
FMT_CONTEXT = 'context'
FORMAT_REPORT = 'report'
FMT_DEFAULT = FMT_UNIFIED
FORMATS = [FMT_UNIFIED, FMT_CONTEXT, FORMAT_REPORT]

SKIP_MODULE = 'module'
SKIP_COMMENT = 'comment'
SKIPABLES = [SKIP_MODULE, SKIP_COMMENT]

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs=2, help="XML menu files 'FILE1 FILE2'")
    parser.add_argument('-f', '--format', choices=FORMATS, default=FMT_DEFAULT, help="select output format")
    parser.add_argument('-s', '--skip', action='append', choices=SKIPABLES, default=[], help="skip information")
    parser.add_argument('-d', '--dump', action='store_true', help="dump the extracted intermediate menu content")
    parser.add_argument('-v', '--verbose', action='count', help="increase output verbosity")
    parser.add_argument('--version', action='version', version="%(prog)s {0}".format(__version__))
    return parser.parse_args()

def main():
    args = parse_args()

    from_file = args.file[0]
    to_file = args.file[1]

    skip = []

    if SKIP_MODULE in args.skip:
        skip.append('module_id')
        skip.append('module_index')

    if SKIP_COMMENT in args.skip:
        skip.append('comment')

    from_menu = menudiff.Menu(from_file, skip)
    to_menu = menudiff.Menu(to_file, skip)

    if args.dump:
        frommenu.dump_intermediate()
        tomenu.dump_intermediate()

    if args.format == FMT_UNIFIED:
        menudiff.unified_diff(
            fromfile=from_menu,
            tofile=to_menu
        )

    if args.format == FMT_CONTEXT:
        menudiff.context_diff(
            fromfile=from_menu,
            tofile=to_menu
        )

    if args.format == FORMAT_REPORT:
        menudiff.report_diff(
            fromfile=from_menu,
            tofile=to_menu,
            verbose=args.verbose > 0
        )

    sys.exit()

if __name__ == '__main__':
    main()
