#!/usr/bin/env python

import argparse
import sys, os

from tmDiff import menudiff

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs=2, help="XML menu files 'FILE1 FILE2'")
    parser.add_argument('-d', '--dump', action='store_true', help="dump the extracted intermediate menu content")
    return parser.parse_args()

def main():
    args = parse_args()

    menudiff.unified_diff(args.file[0], args.file[1], args.dump)

    sys.exit()

if __name__ == '__main__':
    main()
